/**
 * تعریف «جای‌های نمایش» برندینگ - همتای backend/app/services/branding_surfaces.py.
 * پیش‌فرض‌ها باید دقیقاً با سرور یکی باشند (فقط برای حالت آفلاین/قبل از پاسخ سرور).
 */
const LOGIN_LIKE = {
  logo_source: "default",
  default_logo: "app_logo_small",
  logo_size_mobile: 42,
  logo_size_desktop: 48,
  logo_scale: 100,
  frame: "circle",
  frame_color: "#FFFFFF",
  frame_padding: 14,
  title_size_mobile: 15,
  title_size_desktop: 16,
  subtitle_size_mobile: 11,
  subtitle_size_desktop: 11,
  title_color: "#FFFFFF",
  subtitle_color: "rgba(255,255,255,0.85)",
  title_weight: 800,
  background: "linear-gradient(110deg, #3476ad, #2b91a5)",
  show_title: true,
  show_subtitle: true,
};

export const SURFACE_DEFAULTS = {
  splash: {
    logo_source: "default",
    default_logo: "app_logo",
    logo_size_mobile: 120,
    logo_size_desktop: 150,
    logo_scale: 100,
    frame: "none",
    frame_color: "#FFFFFF",
    frame_padding: 0,
    title_size_mobile: 16,
    title_size_desktop: 16,
    subtitle_size_mobile: 14,
    subtitle_size_desktop: 14,
    title_color: "#000000",
    subtitle_color: "#6B7280",
    title_weight: 700,
    background: "#FFFFFF",
    show_title: true,
    show_subtitle: true,
  },
  login: { ...LOGIN_LIKE },
  auth: { ...LOGIN_LIKE },
  sidebar: {
    logo_source: "default",
    default_logo: "app_logo_small",
    logo_size_mobile: 40,
    logo_size_desktop: 40,
    logo_scale: 100,
    frame: "none",
    frame_color: "#FFFFFF",
    frame_padding: 0,
    title_size_mobile: 16,
    title_size_desktop: 16,
    subtitle_size_mobile: 12,
    subtitle_size_desktop: 12,
    title_color: "",
    subtitle_color: "",
    title_weight: 700,
    background: "",
    show_title: true,
    show_subtitle: false,
  },
  profile: {
    logo_source: "default",
    default_logo: "app_logo",
    logo_size_mobile: 84,
    logo_size_desktop: 84,
    logo_scale: 100,
    frame: "circle",
    frame_color: "#FFFFFF",
    frame_padding: 24,
    title_size_mobile: 16,
    title_size_desktop: 16,
    subtitle_size_mobile: 14,
    subtitle_size_desktop: 14,
    title_color: "",
    subtitle_color: "",
    title_weight: 700,
    background: "linear-gradient(135deg, #185E95 0%, #2E84AA 100%)",
    show_title: true,
    show_subtitle: true,
  },
};

/** برچسب‌ها و توضیح هر جای نمایش برای صفحه تنظیمات */
export const SURFACE_META = [
  { key: "splash", label: "اسپلش‌اسکرین", hint: "صفحه معرفی کوتاه هنگام باز شدن اپ.", titleKey: "splash_title", subtitleKey: "splash_subtitle" },
  { key: "login", label: "صفحه ورود", hint: "هدر بالای فرم ورود (موبایل) و پنل کناری (دسکتاپ).", titleKey: "login_title", subtitleKey: "login_subtitle" },
  {
    key: "auth",
    label: "فراموشی / بازیابی رمز",
    hint: "همان چیدمان صفحه ورود؛ متن‌های خالی از صفحه ورود گرفته می‌شوند.",
    titleKey: "auth_title",
    subtitleKey: "auth_subtitle",
  },
  { key: "sidebar", label: "نوار بالای پنل ادمین", hint: "کنار لوگو، بالای منوی کناری.", titleKey: "sidebar_title", subtitleKey: null },
  { key: "profile", label: "پنل کاربری", hint: "هدر صفحه پروفایل هر کاربر.", titleKey: "profile_title", subtitleKey: "profile_subtitle" },
];
